### ISSUE TITLE
jsonStringify outputs with single quotes instead of double quotes

### ISSUE THREAD

**Issue by bbrendon** [DaAwesomeP/upb-cli#5]
I was using your software and was pasting the results into a prettify-er site and it didn't like the single quoted json output. I googled it and it turns out this site says it should be double quote. https://www.json.org/

Luckily it seems my python code doesn't care but just thought I should bring it to your attention.

**Comment by DaAwesomeP** [comment]
Yes, the JSON spec says to use double quotes. I am not specifically controlling the output of the JSON. NodeJS writes pretty JSON to the console in this way. Please try the `--jsonStringify` option to output one line of JSON in the proper spec.

**Comment by bbrendon** [comment]
Oh sorry. You're right. It seems after ingesting it into python it is
removing the double quotes. I'll figure it out. My mistake.
